# Generated by Django 4.2 on 2023-04-21 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('krishan', '0002_contact_delete_blogpost'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='ContactForm',
        ),
        migrations.DeleteModel(
            name='Imagepost',
        ),
    ]
