# Generated by Django 4.2 on 2023-04-22 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishan', '0005_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='pdf_file',
            field=models.FileField(upload_to='cv/'),
        ),
    ]
