# Generated by Django 4.2 on 2023-04-30 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishan', '0006_alter_cv_pdf_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='IMAGE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_krish1', models.ImageField(upload_to='')),
                ('img_krish2', models.ImageField(upload_to='')),
                ('img_testi1', models.ImageField(upload_to='')),
                ('img_testi2', models.ImageField(upload_to='')),
            ],
        ),
    ]
