# Generated by Django 4.2 on 2023-04-30 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishan', '0007_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TEXT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.TextField()),
                ('home1', models.TextField()),
                ('home2', models.TextField()),
                ('home3', models.TextField()),
                ('about1', models.TextField()),
                ('about2', models.TextField()),
                ('about3', models.TextField()),
                ('about4', models.TextField()),
                ('about_name', models.TextField()),
                ('about_email', models.TextField()),
                ('about_linkedin', models.TextField()),
                ('about_instagram', models.TextField()),
                ('skill1', models.TextField()),
                ('skill2', models.TextField()),
                ('skill3', models.TextField()),
                ('skill4', models.TextField()),
                ('skill5', models.TextField()),
                ('testi0', models.TextField()),
                ('testi1', models.TextField()),
                ('testi1_1', models.TextField()),
                ('testi1_2', models.TextField()),
                ('testi2', models.TextField()),
                ('testi2_1', models.TextField()),
                ('testi2_2', models.TextField()),
                ('contact_loc', models.TextField()),
                ('contact_get', models.TextField()),
                ('contact_link', models.TextField()),
                ('last1', models.TextField()),
                ('last2', models.TextField()),
                ('last3', models.TextField()),
            ],
        ),
    ]
