# Generated by Django 4.2 on 2023-04-30 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishan', '0008_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='LINK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github', models.TextField()),
                ('linkedin', models.TextField()),
                ('instagram', models.TextField()),
                ('facebook', models.TextField()),
                ('location', models.TextField()),
            ],
        ),
    ]
