# Generated by Django 4.2 on 2023-05-02 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishan', '0009_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='TITLE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
            ],
        ),
    ]
